// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: post.proto

package postPb

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
	_ "star/proto/community/communityPb"
	_ "star/proto/user/userPb"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PostService service

func NewPostServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PostService service

type PostService interface {
	QueryPostExist(ctx context.Context, in *QueryPostExistRequest, opts ...client.CallOption) (*QueryPostExistResponse, error)
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...client.CallOption) (*CreatePostResponse, error)
	GetPostByPopularity(ctx context.Context, in *GetPostListByPopularityRequest, opts ...client.CallOption) (*GetPostListByPopularityResponse, error)
	GetPostByTime(ctx context.Context, in *GetPostListByTimeRequest, opts ...client.CallOption) (*GetPostListByTimeResponse, error)
	QueryPosts(ctx context.Context, in *QueryPostsRequest, opts ...client.CallOption) (*QueryPostsResponse, error)
}

type postService struct {
	c    client.Client
	name string
}

func NewPostService(name string, c client.Client) PostService {
	return &postService{
		c:    c,
		name: name,
	}
}

func (c *postService) QueryPostExist(ctx context.Context, in *QueryPostExistRequest, opts ...client.CallOption) (*QueryPostExistResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.QueryPostExist", in)
	out := new(QueryPostExistResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...client.CallOption) (*CreatePostResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.CreatePost", in)
	out := new(CreatePostResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) GetPostByPopularity(ctx context.Context, in *GetPostListByPopularityRequest, opts ...client.CallOption) (*GetPostListByPopularityResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.GetPostByPopularity", in)
	out := new(GetPostListByPopularityResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) GetPostByTime(ctx context.Context, in *GetPostListByTimeRequest, opts ...client.CallOption) (*GetPostListByTimeResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.GetPostByTime", in)
	out := new(GetPostListByTimeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postService) QueryPosts(ctx context.Context, in *QueryPostsRequest, opts ...client.CallOption) (*QueryPostsResponse, error) {
	req := c.c.NewRequest(c.name, "PostService.QueryPosts", in)
	out := new(QueryPostsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PostService service

type PostServiceHandler interface {
	QueryPostExist(context.Context, *QueryPostExistRequest, *QueryPostExistResponse) error
	CreatePost(context.Context, *CreatePostRequest, *CreatePostResponse) error
	GetPostByPopularity(context.Context, *GetPostListByPopularityRequest, *GetPostListByPopularityResponse) error
	GetPostByTime(context.Context, *GetPostListByTimeRequest, *GetPostListByTimeResponse) error
	QueryPosts(context.Context, *QueryPostsRequest, *QueryPostsResponse) error
}

func RegisterPostServiceHandler(s server.Server, hdlr PostServiceHandler, opts ...server.HandlerOption) error {
	type postService interface {
		QueryPostExist(ctx context.Context, in *QueryPostExistRequest, out *QueryPostExistResponse) error
		CreatePost(ctx context.Context, in *CreatePostRequest, out *CreatePostResponse) error
		GetPostByPopularity(ctx context.Context, in *GetPostListByPopularityRequest, out *GetPostListByPopularityResponse) error
		GetPostByTime(ctx context.Context, in *GetPostListByTimeRequest, out *GetPostListByTimeResponse) error
		QueryPosts(ctx context.Context, in *QueryPostsRequest, out *QueryPostsResponse) error
	}
	type PostService struct {
		postService
	}
	h := &postServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PostService{h}, opts...))
}

type postServiceHandler struct {
	PostServiceHandler
}

func (h *postServiceHandler) QueryPostExist(ctx context.Context, in *QueryPostExistRequest, out *QueryPostExistResponse) error {
	return h.PostServiceHandler.QueryPostExist(ctx, in, out)
}

func (h *postServiceHandler) CreatePost(ctx context.Context, in *CreatePostRequest, out *CreatePostResponse) error {
	return h.PostServiceHandler.CreatePost(ctx, in, out)
}

func (h *postServiceHandler) GetPostByPopularity(ctx context.Context, in *GetPostListByPopularityRequest, out *GetPostListByPopularityResponse) error {
	return h.PostServiceHandler.GetPostByPopularity(ctx, in, out)
}

func (h *postServiceHandler) GetPostByTime(ctx context.Context, in *GetPostListByTimeRequest, out *GetPostListByTimeResponse) error {
	return h.PostServiceHandler.GetPostByTime(ctx, in, out)
}

func (h *postServiceHandler) QueryPosts(ctx context.Context, in *QueryPostsRequest, out *QueryPostsResponse) error {
	return h.PostServiceHandler.QueryPosts(ctx, in, out)
}
