// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: post.proto

package postPb

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Post service

func NewPostEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Post service

type PostService interface {
	QueryPostExist(ctx context.Context, in *QueryPostExistRequest, opts ...client.CallOption) (*QueryPostExistResponse, error)
}

type postService struct {
	c    client.Client
	name string
}

func NewPostService(name string, c client.Client) PostService {
	return &postService{
		c:    c,
		name: name,
	}
}

func (c *postService) QueryPostExist(ctx context.Context, in *QueryPostExistRequest, opts ...client.CallOption) (*QueryPostExistResponse, error) {
	req := c.c.NewRequest(c.name, "Post.QueryPostExist", in)
	out := new(QueryPostExistResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Post service

type PostHandler interface {
	QueryPostExist(context.Context, *QueryPostExistRequest, *QueryPostExistResponse) error
}

func RegisterPostHandler(s server.Server, hdlr PostHandler, opts ...server.HandlerOption) error {
	type post interface {
		QueryPostExist(ctx context.Context, in *QueryPostExistRequest, out *QueryPostExistResponse) error
	}
	type Post struct {
		post
	}
	h := &postHandler{hdlr}
	return s.Handle(s.NewHandler(&Post{h}, opts...))
}

type postHandler struct {
	PostHandler
}

func (h *postHandler) QueryPostExist(ctx context.Context, in *QueryPostExistRequest, out *QueryPostExistResponse) error {
	return h.PostHandler.QueryPostExist(ctx, in, out)
}
