// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: channels.proto

package channelsPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendToServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommunityId int64 `protobuf:"varint,1,opt,name=CommunityId,proto3" json:"CommunityId,omitempty"`
}

func (x *SendToServerRequest) Reset() {
	*x = SendToServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channels_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToServerRequest) ProtoMessage() {}

func (x *SendToServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channels_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToServerRequest.ProtoReflect.Descriptor instead.
func (*SendToServerRequest) Descriptor() ([]byte, []int) {
	return file_channels_proto_rawDescGZIP(), []int{0}
}

func (x *SendToServerRequest) GetCommunityId() int64 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

type SendToServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendToServerResponse) Reset() {
	*x = SendToServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channels_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToServerResponse) ProtoMessage() {}

func (x *SendToServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_channels_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToServerResponse.ProtoReflect.Descriptor instead.
func (*SendToServerResponse) Descriptor() ([]byte, []int) {
	return file_channels_proto_rawDescGZIP(), []int{1}
}

type SendToClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendToClientRequest) Reset() {
	*x = SendToClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channels_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToClientRequest) ProtoMessage() {}

func (x *SendToClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channels_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToClientRequest.ProtoReflect.Descriptor instead.
func (*SendToClientRequest) Descriptor() ([]byte, []int) {
	return file_channels_proto_rawDescGZIP(), []int{2}
}

type SendToClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendToClientResponse) Reset() {
	*x = SendToClientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_channels_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToClientResponse) ProtoMessage() {}

func (x *SendToClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_channels_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToClientResponse.ProtoReflect.Descriptor instead.
func (*SendToClientResponse) Descriptor() ([]byte, []int) {
	return file_channels_proto_rawDescGZIP(), []int{3}
}

var File_channels_proto protoreflect.FileDescriptor

var file_channels_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x37, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x43, 0x6f,
	0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64,
	0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x8a, 0x01, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x3e, 0x0a,
	0x0f, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x12, 0x14, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a,
	0x0f, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x12, 0x14, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a,
	0x0c, 0x2e, 0x3b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x50, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_channels_proto_rawDescOnce sync.Once
	file_channels_proto_rawDescData = file_channels_proto_rawDesc
)

func file_channels_proto_rawDescGZIP() []byte {
	file_channels_proto_rawDescOnce.Do(func() {
		file_channels_proto_rawDescData = protoimpl.X.CompressGZIP(file_channels_proto_rawDescData)
	})
	return file_channels_proto_rawDescData
}

var file_channels_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_channels_proto_goTypes = []interface{}{
	(*SendToServerRequest)(nil),  // 0: SendToServerRequest
	(*SendToServerResponse)(nil), // 1: SendToServerResponse
	(*SendToClientRequest)(nil),  // 2: SendToClientRequest
	(*SendToClientResponse)(nil), // 3: SendToClientResponse
}
var file_channels_proto_depIdxs = []int32{
	0, // 0: Channels.SendMsgToServer:input_type -> SendToServerRequest
	2, // 1: Channels.SendMsgToClient:input_type -> SendToClientRequest
	1, // 2: Channels.SendMsgToServer:output_type -> SendToServerResponse
	3, // 3: Channels.SendMsgToClient:output_type -> SendToClientResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_channels_proto_init() }
func file_channels_proto_init() {
	if File_channels_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_channels_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_channels_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_channels_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_channels_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToClientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_channels_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_channels_proto_goTypes,
		DependencyIndexes: file_channels_proto_depIdxs,
		MessageInfos:      file_channels_proto_msgTypes,
	}.Build()
	File_channels_proto = out.File
	file_channels_proto_rawDesc = nil
	file_channels_proto_goTypes = nil
	file_channels_proto_depIdxs = nil
}
