// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

package userPb

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	LoginPassword(ctx context.Context, in *LSRequest, opts ...client.CallOption) (*LoginResponse, error)
	LoginCaptcha(ctx context.Context, in *LSRequest, opts ...client.CallOption) (*LoginResponse, error)
	Signup(ctx context.Context, in *LSRequest, opts ...client.CallOption) (*EmptyLSResponse, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...client.CallOption) (*GetUserInfoResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) LoginPassword(ctx context.Context, in *LSRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.LoginPassword", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) LoginCaptcha(ctx context.Context, in *LSRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.LoginCaptcha", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Signup(ctx context.Context, in *LSRequest, opts ...client.CallOption) (*EmptyLSResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.Signup", in)
	out := new(EmptyLSResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...client.CallOption) (*GetUserInfoResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserInfo", in)
	out := new(GetUserInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	LoginPassword(context.Context, *LSRequest, *LoginResponse) error
	LoginCaptcha(context.Context, *LSRequest, *LoginResponse) error
	Signup(context.Context, *LSRequest, *EmptyLSResponse) error
	GetUserInfo(context.Context, *GetUserInfoRequest, *GetUserInfoResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		LoginPassword(ctx context.Context, in *LSRequest, out *LoginResponse) error
		LoginCaptcha(ctx context.Context, in *LSRequest, out *LoginResponse) error
		Signup(ctx context.Context, in *LSRequest, out *EmptyLSResponse) error
		GetUserInfo(ctx context.Context, in *GetUserInfoRequest, out *GetUserInfoResponse) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) LoginPassword(ctx context.Context, in *LSRequest, out *LoginResponse) error {
	return h.UserServiceHandler.LoginPassword(ctx, in, out)
}

func (h *userServiceHandler) LoginCaptcha(ctx context.Context, in *LSRequest, out *LoginResponse) error {
	return h.UserServiceHandler.LoginCaptcha(ctx, in, out)
}

func (h *userServiceHandler) Signup(ctx context.Context, in *LSRequest, out *EmptyLSResponse) error {
	return h.UserServiceHandler.Signup(ctx, in, out)
}

func (h *userServiceHandler) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, out *GetUserInfoResponse) error {
	return h.UserServiceHandler.GetUserInfo(ctx, in, out)
}
