// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

package userPb

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for User service

func NewUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for User service

type UserService interface {
	LoginPassword(ctx context.Context, in *LSRequest, opts ...client.CallOption) (*LoginResponse, error)
	LoginCaptcha(ctx context.Context, in *LSRequest, opts ...client.CallOption) (*LoginResponse, error)
	Signup(ctx context.Context, in *LSRequest, opts ...client.CallOption) (*EmptyLSResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) LoginPassword(ctx context.Context, in *LSRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "User.LoginPassword", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) LoginCaptcha(ctx context.Context, in *LSRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "User.LoginCaptcha", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Signup(ctx context.Context, in *LSRequest, opts ...client.CallOption) (*EmptyLSResponse, error) {
	req := c.c.NewRequest(c.name, "User.Signup", in)
	out := new(EmptyLSResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	LoginPassword(context.Context, *LSRequest, *LoginResponse) error
	LoginCaptcha(context.Context, *LSRequest, *LoginResponse) error
	Signup(context.Context, *LSRequest, *EmptyLSResponse) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		LoginPassword(ctx context.Context, in *LSRequest, out *LoginResponse) error
		LoginCaptcha(ctx context.Context, in *LSRequest, out *LoginResponse) error
		Signup(ctx context.Context, in *LSRequest, out *EmptyLSResponse) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) LoginPassword(ctx context.Context, in *LSRequest, out *LoginResponse) error {
	return h.UserHandler.LoginPassword(ctx, in, out)
}

func (h *userHandler) LoginCaptcha(ctx context.Context, in *LSRequest, out *LoginResponse) error {
	return h.UserHandler.LoginCaptcha(ctx, in, out)
}

func (h *userHandler) Signup(ctx context.Context, in *LSRequest, out *EmptyLSResponse) error {
	return h.UserHandler.Signup(ctx, in, out)
}
